# Generated by Django 2.2.7 on 2021-03-31 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('likes', models.IntegerField(default=-99999)),
                ('shortcont', models.CharField(blank=True, max_length=230)),
                ('posting_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='fontstyles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gradient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(default='', max_length=50)),
                ('color2', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=99999)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Theme', max_length=70)),
                ('textcolor', models.CharField(blank=True, default='', max_length=50)),
                ('titlecolor', models.CharField(blank=True, default='', max_length=50)),
                ('textfont', models.CharField(blank=True, default='', max_length=200)),
                ('titlefont', models.CharField(blank=True, default='', max_length=200)),
                ('gradient', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='home.Gradient')),
            ],
        ),
        migrations.CreateModel(
            name='defaultthemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default', to='home.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentby', to='home.Feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('title', models.CharField(default='blogger', max_length=30)),
                ('BP', models.IntegerField(default=0)),
                ('signup_date', models.DateTimeField()),
                ('Username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogger', to='home.Username')),
                ('article', models.ManyToManyField(blank=True, related_name='blogger', to='home.Article')),
                ('theme', models.ManyToManyField(blank=True, default='', related_name='blogger', to='home.Theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogger', to='home.User')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post', to='home.Comments'),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='post', to='home.Paragraphs'),
        ),
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='post', to='home.Theme'),
        ),
    ]
